version: '3'
services:
  api:
    image: node:7
    working_dir: /root
    volumes:
      - ./api:/root
    ports:
      - 8001:80
    command: 'npm start'
  client:
    image: node:7
    working_dir: /root
    volumes:
      - ./client:/root
    ports:
      - 8002:80
    command: 'npm start'
    depends_on:
      - api
